blog/config/routes.rb
Blog::Application.routes.draw do
  resources :teas do
    resources :comments
  end

  get "home/index"

   root :to => 'home#index'

end

blog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :tea
end

blog/app/models/tea.rb
class Tea < ActiveRecord::Base
  validates :type_of_fluid, numericality:  {less_than: 10 }
  has_many :comments, dependent: :destroy
  translates :extra_content
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_locale, :set_user_language 
  def set_user_language
    I18n.locale = $locale#request.params["locale"] || "pl"
    
  end
  
  
  
  def set_locale
    $locale = request.params["locale"] if request.params["locale"]
  end
  protected
  $locale = "en"
  
end

blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    @tea = Tea.find(params[:tea_id])
    @comment = @tea.comments.create(params[:comment])
    redirect_to tea_path(@tea)
  end
  
  def destroy
    @tea = Tea.find(params[:tea_id])
    @comment = @tea.comments.find(params[:id])
    @comment.destroy
    redirect_to tea_path(@tea)
  end
end

blog/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

blog/app/controllers/teas_controller.rb
class TeasController < ApplicationController
  # GET /teas
  # GET /teas.json
  def index
    @teas = Tea.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @teas }
    end
  end

  # GET /teas/1
  # GET /teas/1.json
  def show
    @tea = Tea.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tea }
    end
  end

  # GET /teas/new
  # GET /teas/new.json
  def new
    @tea = Tea.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tea }
    end
  end

  # GET /teas/1/edit
  def edit
    @tea = Tea.find(params[:id])
  end

  # POST /teas
  # POST /teas.json
  def create
    @tea = Tea.new(params[:tea])

    respond_to do |format|
      if @tea.save
        format.html { redirect_to @tea, notice: 'Tea was successfully created.' }
        format.json { render json: @tea, status: :created, location: @tea }
      else
        format.html { render action: "new" }
        format.json { render json: @tea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /teas/1
  # PUT /teas/1.json
  def update
    @tea = Tea.find(params[:id])

    respond_to do |format|
      if @tea.update_attributes(params[:tea])
        format.html { redirect_to @tea, notice: 'Tea was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teas/1
  # DELETE /teas/1.json
  def destroy
    @tea = Tea.find(params[:id])
    @tea.destroy

    respond_to do |format|
      format.html { redirect_to teas_url }
      format.json { head :no_content }
    end
  end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/comments_helper.rb
module CommentsHelper
end

blog/app/helpers/home_helper.rb
module HomeHelper
end

blog/app/helpers/teas_helper.rb
module TeasHelper
end

blog/app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<%= link_to "My Teas", teas_path %>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav style="float:right;">
<%= link_to  "English", locale: "en"%>
<%= link_to "Polish", locale: "pl"%>
</nav>
<%= t 'hello' %>
<%= yield %><br>
</body>
</html>

blog/app/views/teas/_form.html.erb
<%= form_for(@tea) do |f| %>
  <% if @tea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tea.errors.count, "error") %> prohibited this tea from being saved:</h2>

      <ul>
      <% @tea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :producer %><br />
    <%= f.text_field :producer %>
  </div>
  <div class="field">
    <%= f.label :type_of_fluid %><br />
    <%= f.number_field :type_of_fluid %>
  </div>
  <div class="field">
    <%= f.label :webpage %><br />
    <%= f.text_field :webpage %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :extra_content %><br />
    <%= f.text_area :extra_content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

blog/app/views/teas/_image.html.erb
  <% if @tea.image.include? "http"%>
  <img src="<%= @tea.image %>" />
  <%else%>
    <%= image_tag('noimage.png', :alt=>"no image") %>
  <%end%>

blog/app/views/teas/_type_of_fluid.html.erb
<%= case @tea.type_of_fluid
  when 1 then "Tea"
  when 2 then "Tea-like"
  when 3 then "Coffe"
  end
%>

blog/app/views/teas/_webpage.html.erb
<% if @tea.webpage.include? "http" %>
<a href="<%=@tea.webpage%>">website</a>
<% else %>Unavaible
<%end%>

blog/app/views/teas/edit.html.erb
<h1>Editing tea</h1>

<%= render 'form' %>

<%= link_to 'Show', @tea %> |
<%= link_to 'Back', teas_path %>

blog/app/views/teas/index.html.erb
<h1>Listing teas</h1>

<table border="1px dashed">
  <tr>
    <th><%= (t 'name').capitalize%></th>
    <th><%= (t 'producer') .capitalize%></th>
    <th><%= (t 'type_of_fluid') .capitalize%></th>
    <th><%= (t 'webpage') .capitalize%></th>
    <th><%= (t 'image') .capitalize%></th>
    <th><%= (t 'extra_content') .capitalize%></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @teas.each do |tea| @tea=tea %>
  <tr>
    <td><%= tea.name %></td>
    <td><%= tea.producer %></td>
    <td>  <%= render "type_of_fluid" %> </td>
    <!-- <td><a href="<%=tea.webpage%>">website</a></td> -->
    <td><%= render "teas/webpage" %></td>
    <!--<td><img src="<%= tea.image %>" /></td> -->
    <td><%= render "teas/image" %></td>
    <td><%= tea.extra_content %></td>
    <td><%= link_to 'Show', tea %></td>
    <td><%= link_to 'Edit', edit_tea_path(tea) %></td>
    <td><%= link_to 'Destroy', tea, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tea', new_tea_path %>

blog/app/views/teas/new.html.erb
<h1>New tea</h1>

<%= render 'form' %>

<%= link_to 'Back', teas_path %>

blog/app/views/teas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @tea.name %>
</p>

<p>
  <b>Producer:</b>
  <%= @tea.producer %>
</p>

<p>
  <b>Type of fluid:</b>
  <%= render "type_of_fluid" %>
</p>

<p>
  <b>Webpage:</b>
  <%#= @tea.webpage %>
  <%#= link_to "website", @tea.webpage %>
  <!-- <a href="<%=@tea.webpage%>">website</a> -->
  <%= render "webpage" %>
</p>

<p>
  <b>Image:</b>
  <%= render "image" %>
</p>

<p>
  <b>Extra content:</b>
  <%= @tea.extra_content %>
</p>

<h2>Comments</h2>
<% @tea.comments.each_with_index do |f, i| %>
  <div class="comments">
  <h3>Commenter nr.<%=i%>:</h3>
  <% if f.body.length >50 %>
    <h1>DLUGI KOMENT</h1>
  <%end%>
    
  <%=f.commenter%>
  <h3>Comment: </h3>
  <%=  truncate(f.body, length: 50, separator: ' ' )  %><br>
  <%#= f.body %>
  <%= link_to "Destroy comment", [f.tea, f],
              :confirm => "Are you sure?",
              :method => "delete"
  %>
  </div>
<%end%>

<h2>Add a comment:</h2>
<%= form_for([@tea, @tea.comments.build]) do |f| %>
  <div class="field">
    <%= f.label :commenter %><br />
    <%= f.text_field :commenter %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Edit', edit_tea_path(@tea) %> |
<%= link_to 'Back', teas_path %>